messagebroker:
  url: "tcp://localhost:61616"

database:
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/sampleuserstoredb"
  username: "root"
  password: "root"

server:
  connectionlimit: 2
